// autogenerated by xop-stub-generator.pl from interface.h
// vim: set ft=rc:
#include "XOPStandardHeaders.r"      // Defines XOP-specific symbols.

resource 'XOPF' (1100) {   // Describes functions added by XOP to IGOR.
  {
    
  // variable MU_GetFreeDiskSpace(string path)
  "MU_GetFreeDiskSpace",
  F_UTIL | F_EXTERNAL,    // Function category
  NT_FP64,          // Return value type
  {
      HSTRING_TYPE,      // parameter 1
  },

  // variable MU_RunningInMainThread()
  "MU_RunningInMainThread",
  F_UTIL | F_EXTERNAL | F_THREADSAFE,    // Function category
  NT_FP64,          // Return value type
  {
    
  },

  // variable MU_WaveModCount(WAVE input)
  "MU_WaveModCount",
  F_UTIL | F_EXTERNAL,    // Function category
  NT_FP64,          // Return value type
  {
      WAVE_TYPE,      // parameter 1
  },

  }
};
